### ISSUE TITLE
✅ [23.11.22] 폰트어썸, Material-UI 세팅

### ISSUE THREAD

**Issue by s-ja** [techitPlus-FE-team3/open_market_projerct#1]
## Todo
- [x] 폰트어썸 패키지 설치
- [x] Material-UI 아이콘 패키지 설치
- [ ] 폰트어썸 테스트
- [ ] Material-UI 테스트
- [ ] ~~SVG 사용시와 비교~~

## 기타

폰트어썸과 Material-UI 둘다 설치하여 사용할지 의문,
SVG 로 만들거나 가져오는 방식과 비교하여 편의성 및 성능적으로 개선이 있을지 확인 필요.
