### ISSUE TITLE
✅ [23.11.30] 로그아웃 기능 생성

### ISSUE THREAD

**Issue by s-ja** [techitPlus-FE-team3/open_market_projerct#119]
## Todo
- [ ] 헤더 마크업 수정
- [ ] 로컬 스토리지 비우는 것으로 기능 구현
- [ ] 전역 상태로 관리중인 로그인 상태 초기화
