### ISSUE TITLE
✅ [23.12.01] order 관련 코드 수정

### ISSUE THREAD

**Issue by hungerbk** [techitPlus-FE-team3/open_market_projerct#136]
## Todo
- [x] order 생성 시 user extra로 들어가는 코드 삭제
- [x] product detail에서 order 불러오는 코드 수정
- [x] 로그인 상태 확인 코드 수정
