### ISSUE TITLE
✅ [23.12.05] API 변경에 맞게 interface 수정

### ISSUE THREAD

**Issue by hungerbk** [techitPlus-FE-team3/open_market_projerct#153]
## Todo
- [x] API 변경에 맞게 Product 인터페이스 수정
- [x] API 변경에 맞게 Reply 인터페이스 수정
- [x] API 변경에 맞게 Order 인터페이스 수정
- [x] API 변경에 맞게 Bookmark 인터페이스 추가
