### ISSUE TITLE
✅ [23.12.05] 유저 상품 판매 목록 정렬 기능 구현

### ISSUE THREAD

**Issue by pearlKinn** [techitPlus-FE-team3/open_market_projerct#172]
## Todo
- [x] 유저 판매 상품 정렬 기능 만들기
- [x] itemWithExporeTime 유틸함수 생성
- [x] numberWithComma 유틸함수 생성
