### ISSUE TITLE
✅ [23.12.11] api 변경에 따른 상품 등록 및 수정 파일 업로드 수정

### ISSUE THREAD

**Issue by pearlKinn** [techitPlus-FE-team3/open_market_projerct#211]
## Todo
- [ ] 상품등록 페이지 수정
- [ ] 상품 수정 페이지 수정
- [ ] uploadFile 함수 수정
