### ISSUE TITLE
✅ [23.12.11] 상품 리스트 컴포넌트 생성 및 스타일링

### ISSUE THREAD

**Issue by hungerbk** [techitPlus-FE-team3/open_market_projerct#216]
## Todo
- [ ] 리스트 음원 재생 바 스타일링
- [ ] 메인 페이지, 구매내역에서 보일 상품 리스트 컴포넌트 생성 및 스타일링
- [ ] 기본 리스트와 구매내역 리스트 컴포넌트를 props로 구분하여 import

## 기타

판매내역 컴포넌트도 props로 관리할지 별도의 컴포넌트를 생성할지 논의 필요
