### ISSUE TITLE
✅ [23.12.15] 디테일 리팩토링

### ISSUE THREAD

**Issue by pearlKinn** [techitPlus-FE-team3/open_market_projerct#250]
## Todo
- [x] 로그아웃 시 로컬 및 세션 비우기
- [x] 마이페이지 눌렀을 떄 / 로고 눌렀을 때 로컬 비우기
- [ ] #260
- [x] 라디오 버튼 선택되지 않는 버그 수정
- [x] 서치키워드 함수 toLowerCase
- [x] 구매 완료 시 메인페이지 -> 구매 내역 페이지로 이동
- [ ] #261
- [x] handleSearchKeyWord 화살표 함수 -> 선언식
