### ISSUE TITLE
✅ [23.12.17] 디테일 페이지 스타일 작업

### ISSUE THREAD

**Issue by hungerbk** [techitPlus-FE-team3/open_market_projerct#255]
## Todo
- [ ] 디테일 페이지 상품 정보 스타일 작업
- [ ] 뱃지 및 버튼 컴포넌트 생성 및 스타일 작업
- [ ] 디테일 페이지 용 플레이 컴포넌트 생성(임시)
