### ISSUE TITLE
✅ [23.12.19] 컴포넌트 로딩중 스켈레톤 표시

### ISSUE THREAD

**Issue by s-ja** [techitPlus-FE-team3/open_market_projerct#263]
## 작업 사항

배포 이후 각 페이지의 로딩에 시간이 많이 소요되는 것을 확인, 각각의 컴포넌트가 로딩중일때 해당 영역에 스켈레톤 UI를 표시하게끔 하는 기능 구현 필요

## Todo
- [x] MUI 스켈레톤 UI 컴포넌트 조사
- [x] 스켈레톤 표시 유틸리티 구성
- [x] 필요 컴포넌트에 적용
