### ISSUE TITLE
✅ [23.12.19] 검색, 필터, 정렬 리팩토링

### ISSUE THREAD

**Issue by pearlKinn** [techitPlus-FE-team3/open_market_projerct#266]
## Todo
- [x]  구매 내역 검색 필터 정렬 리팩토링
- [x] 상품관리 내역 검색 필터 정렬 리팩토링
- [x] 상품 내역 검색 필터 정렬 리팩토링
