### ISSUE TITLE
✅ [23.12.19] 디테일 페이지 & 판매상품 관리 리팩토링

### ISSUE THREAD

**Issue by hungerbk** [techitPlus-FE-team3/open_market_projerct#269]
## Todo
- [x] 디테일 페이지 셀러 아이디 대신 셀러 이름 불러오도록 수정
- [x] 뱃지 컨테이너 레이아웃 수정
- [x] 댓글 유저 이미지 가져 오도록 수정
- [x] 제품 상세정보 페이지 업로드 날짜 수정(날짜만 보이고 시간 안 보이게끔)
- [x] 상품 관리 페이지에 판매 수익 numberWithComma 함수 추가
- [x] 판매 관리 페이지에서 판매 금액도 확인할 수 있도록 수정
- [x] 상품 삭제 후 판매 상품 관리 페이지로 이동
- [x] favicon 경로 수정
