### ISSUE TITLE
✅ [23.12.20] 헤더 스타일 수정 및 페이지 레이아웃 수정

### ISSUE THREAD

**Issue by s-ja** [techitPlus-FE-team3/open_market_projerct#276]
## Todo
- [ ] index.html body태그 배경색 추가
- [ ] 헤더 상단에 위치 고정
- [ ] 헤더 코드 수정으로 인한 다른 페이지들 레이아웃(스타일) 수정
