### ISSUE TITLE
✅ [23.12.21] 세부 리팩토링

### ISSUE THREAD

**Issue by hungerbk** [techitPlus-FE-team3/open_market_projerct#287]
## Todo
- [x] 토스트 코드, 멘트 통일
- [x] 상품 가격 입력 시 음수 막기
- [x] 상품 관리 페이지에서 상품 상세 페이지 이동가능 하게 수정
- [x] 상품 관리 페이지 말고 판매내역 리스트에서도 상품 공개/비공개 여부 확인 가능하게
- [x] 구매페이지 셀러 아이디가 아닌 셀러 이름 표기
- [x] textarea 크기 지정
- [x] 상품 관리 페이지에서 판매내역 리스트로 이동 가능하게 링크 추가
