### ISSUE TITLE
✅ [23.12.22] 추가 페이지 작업

### ISSUE THREAD

**Issue by hungerbk** [techitPlus-FE-team3/open_market_projerct#290]
## Todo
- [x] 로딩 페이지 작업
- [x] 404 에러 페이지 작업
- [x] 404 에러 이동 추가 작업
- [x] alt 통일
- [x] 해시태그 저장 시 공백 제거
- [x] 댓글 별점 부분 수정(배경색과 같아서 보이지 않음)
- [x] 코드 스타일 통일
- [x] 주석 제거
