### ISSUE TITLE
✅ [24.04.12] 리액트 헬멧 수정 및 메타 태그 개선

### ISSUE THREAD

**Issue by s-ja** [techitPlus-FE-team3/open_market_projerct#319]
## 작업 사항

- 현재 react helmet에는 페이지 타이틀만 추가되어 있는 상황.

## Todo
- [x] 메타 태그 추가를 통한 검색 엔진 최적화 작업
- [x] 오픈 그래프 추가를 통한 링크 공유 시의 사이트 표시 방법 개선
- [x] Canonical URL(페이지 기준 URL) 설정을 통한 SEO 중복 콘텐츠 문제 해결

## 기타

- 조사와 병행하여 추가 작업 사항이 생길 경우 해당 이슈에 추가 예정
