### ISSUE TITLE
✅ [24.04.21] 마이페이지 회원 정보 표시 영역 조정

### ISSUE THREAD

**Issue by s-ja** [techitPlus-FE-team3/open_market_projerct#350]
## 작업 사항

- 마이페이지 회원 정보(이메일, 이름, 휴대폰 번호)표시 칸과 댓글 텍스트가 너무 작은 문제 해결

## Todo
- [x] 마이페이지 회원 정보 표시 칸 레이아웃 조정
- [x] 마이페이지 댓글 표시 칸 레이아웃 조정
- [x] 적절한 텍스트 크기 조정
