### ISSUE TITLE
✅ [24.04.21] 상품 리스트 컴포넌트 리팩토링

### ISSUE THREAD

**Issue by hungerbk** [techitPlus-FE-team3/open_market_projerct#358]
## Todo
- [x] 상품 리스트 북마크 > 버튼 태그에서 상품 북마크 개수 보여주는 걸로 변경
- [x] list에서 product name 옆에 > 아이콘을 넣어서 클릭하면 다른 곳으로 이동할 것이라는 걸 명시
- [x] 음원 로드 중 표시 > meta 데이터 이용하여 음원이 재생 준비가 된 경우 표시 그 전에는 스켈레톤 ui
