### ISSUE TITLE
✅ [24.04.23] 북마크 테스트 코드 작성

### ISSUE THREAD

**Issue by pearlKinn** [techitPlus-FE-team3/open_market_projerct#361]
## Todo
- [x] 북마크 등록 버튼 api
- [x] 북마크 취소 api
- [x] 북마크 리스트 api
- [x] 북마크 정보 api
- [x] 북마크 뮤테이션
