### ISSUE TITLE
✅ [24.04.24] 댓글 컴포넌트 리팩토링

### ISSUE THREAD

**Issue by hungerbk** [techitPlus-FE-team3/open_market_projerct#366]
## Todo
- [x] 댓글 내용이 없을 때 댓글 작성 불가하게 수정
- [x] 댓글 업로드 중을 유저에게 표시
- [x] 댓글 업로드 중 작성하기 버튼 재클릭하여 중복 호출 방지
