### ISSUE TITLE
✅ [24.04.25] 댓글 테스트 코드 작성

### ISSUE THREAD

**Issue by hungerbk** [techitPlus-FE-team3/open_market_projerct#373]
## Todo
- [x] 댓글 등록 api
- [x] 댓글 등록 mutation
- [x] 상품 정보 get api
- [x] 유저 오더 get api
- [x] 댓글 리스트 api
- [ ] 유저 상태에 따른 product detail 페이지 ui 테스트
