### ISSUE TITLE
✅ [24.04.24] 토큰 갱신 기능 테스트 코드 작성

### ISSUE THREAD

**Issue by s-ja** [techitPlus-FE-team3/open_market_projerct#375]
## 작업 사항

- 토큰 갱신 기능 테스트
- 모든 요청에서 사용하고 있는 axiosInstance 테스트
- 현재 401에러로 작동하지 않고 있는 토큰 갱신 기능 수정

## Todo
- [ ] 토큰 만료 상황에서 리프레시 토큰을 이용한 토큰 갱신이 제대로 이뤄지는지 테스트 코드 작성
- [x] 현재의 토큰 갱신 기능 오류 원인 추적
  - `promise`를 이용한 요청 중복 처리 수정 이후 작동하던 토큰 갱신 기능이 최근 다시 작동하지 않는 이슈
  - 리프레시 토큰 만료시 로그인 화면으로 이동하는 기능의 경우, 새로고침을 해야지만 작동하는 이슈
  - 한 페이지에서 계속 머무르는 중 토큰 만료 시 새로고침을 해야지만 토큰 갱신이 작동하는 이슈
- [ ] api 요청에 사용중인 `axiosInstance`에 대한 테스트 코드 작성

## 기타

- 확인 후 `axiosInstance`에 대한 테스트는 필요 없을 시 진행하지 않을 예정
- 토큰 갱신 기능 코드의 작성과 현재의 에러 추적은 병행하여 진행될 예정
- 에러 추적 및 테스트 코드 구축 과정에서 작업 방향은 수정될 수 있음
