### ISSUE TITLE
✅ [23.11.24] 공통 interface 생성

### ISSUE THREAD

**Issue by hungerbk** [techitPlus-FE-team3/open_market_projerct#39]
## 작업 사항

공통 interface 생성

## Todo
- [x] 회원정보 인터페이스 생성
- [x] 상품 인터페이스 생성
- [x] 구매 인터페이스 생성
