### ISSUE TITLE
✅ [24.05.18] 사용자 인증, 수정, 관리 관련 테스트 코드 작성 및 수정 #374

### ISSUE THREAD

**Issue by s-ja** [techitPlus-FE-team3/open_market_projerct#392]
## 작업 사항

![image](https://github.com/techitPlus-FE-team3/open_market_projerct/assets/69342971/0a974fb7-329a-4eec-b528-93d7dc98d5d3)
- 로그인, 회원가입, 로그아웃 기능 관련 테스트 코드 재구성

## Todo
- [x] API 호출 함수 단위 테스트 : `src/apis/user/auth.ts`에 대한 테스트 코드 작성
  - 로그인
  - 회원가입
  - 회원정보 수정 
- [x] 커스텀 훅 단위 테스트 : `src/hooks/user` 내부에 구성한 커스텀 훅 테스트 코드 작성
  - 로그인 `useSignInMutation`
  - 회원가입 `useSignUpMutation`
  - 회원 정보 수정 `useUpdateUserMutation`
- [ ] 각 페이지별 UI 렌더링 테스트 : 기존 작성한 코드 보수 및 구성
  - [x] 로그인 페이지 (재구성 혹은 보수)
  - [x] 회원가입 페이지
  - [ ] 회원 정보 수정 페이지 
- [ ] 페이지별 통합 테스트 : 각 페이지별 커스텀 훅 마운트 이후 전체적인 기능이 제대로 작동하는 지 확인
  - [x] 로그인 페이지
  - [ ] 회원가입 페이지
  - [ ] 회원정보 수정 페이지 
- [ ] 기존 작성 테스트 코드 수정

## 기타

- 현재 작동하는 헤더 컴포넌트(로그아웃)의 경우에도 작업 진행과 함께 UI 렌더링과 기능 테스트 부분을 분리해야 할 경우 분리할 예정
