### ISSUE TITLE
✅ [23.11.27] 상품 구매 페이지 마크업 수정

### ISSUE THREAD

**Issue by pearlKinn** [techitPlus-FE-team3/open_market_projerct#49]
## 작업 사항

상품 구매 페이지 마크업 수정 및 라우터 수정

## Todo
- [x] 상품 구매페이지 (설명 ↔️ 가격) 마크업 변경 
- [x] 음원 업로드 마크업 추가
- [x] 라우터 주소 수정 (registration -> productregistration)
