### ISSUE TITLE
✅ [23.11.23] 상세 페이지 마크업

### ISSUE THREAD

**Issue by s-ja** [techitPlus-FE-team3/open_market_projerct#6]
## Todo
- [x] 메인 섹션 마크업
    - 앨범아트 + 플레이 버튼
    - 음원 정보
    - 플레이 미터
- [x] 기능 섹션 마크업
    - 북마크 버튼, 구매 버튼
- [x] 댓글 리스트 마크업
