### ISSUE TITLE
✅ [23.11.29] 음원 장르 데이터 생성

### ISSUE THREAD

**Issue by s-ja** [techitPlus-FE-team3/open_market_projerct#90]
## Todo
- [ ] Data 폴더 생성
- [ ] genre.ts 폴더 생성
- [ ] sellbuymusic 의 장르들을 배열 형태로 export
- [ ] import이후 map으로 활용하게끔 설정
